# # version: '3.8'

# services:
#   db:
#     image: postgres:14-alpine
#     container_name: ba_postgres_db
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: olan
#       POSTGRES_DB: quarkus_test
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: